---
title:  "try-catch 예외 처리" 

categories:
  -  JAVA Concepts
tags:
  - [Programming, JAVA 개념]

toc: true
toc_sticky: true

date: 2021-03-09
last_modified_at: 
---


<br>

# 예외 처리

> 자바의 예외 처리는 try - catch 를 사용 .

　`오류`를 `발생시킬` 수 있는 부분은 `try` 로 감싸고 

　`오류`가 `발생할` 경우 `catch` 에서 `처리` 하는 개념 이다 .   

## 예제
```java
public class Main {
    public static void main(String[] args){
        int[] array = new int[3];

        for (int i = 0; i < 10; i++){
            array[i] = i;
        }

        for(int i : array){
            System.out.println(i);
        }
    }
}
```
```
　Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3 
at Main.main(Main.java:6)
```

　배열 `array` 의 `크기`가 `3` 인데 `for 문` 에서 `i` 를 `10` 까지 돌려서 인덱스가 범위를 벗어났다는   

　`ArrayIndexOutOfBoundsException` 에러가 발생했다 .

　예외 처리가 필요한 코드의 흐름에서 `try-catch` 를 사용해서 처리해 보자 .

```java
public class Main {
    public static void main(String[] args){
        int[] array = new int[3];

        for (int i = 0; i < 10; i++){
            try {
                array[i] = i;
            } catch (ArrayIndexOutOfBoundsException e){
                System.out.println(i + "번 째 시도에서 예외 발생");
            }
        }
        for(int i : array){
            System.out.println(i);
        }
    }
}
```
```
3번 째 시도에서 예외 발생
4번 째 시도에서 예외 발생
5번 째 시도에서 예외 발생
6번 째 시도에서 예외 발생
7번 째 시도에서 예외 발생
8번 째 시도에서 예외 발생
9번 째 시도에서 예외 발생
0
1
2
```

　`예외 처리` 가 되어 프로그램이 죽지 않고 array 출력까지 된 것을 확인 할 수 있다 .
<br>

***

개인 기록용 스터디 블로그 입니다.
{: .notice--warning}

[맨 위로 이동하기](#){: .btn .btn--primary }{: .align-right}